steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cardiovascular-ecg-app', '.']
    dir: 'Deployment'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cardiovascular-ecg-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'cardiovascular-ecg-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cardiovascular-ecg-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
    entrypoint: 'gcloud'

images:
  - 'gcr.io/$PROJECT_ID/cardiovascular-ecg-app'